### ISSUE TITLE
DiscordRPC 5.0.10

### ISSUE THREAD

**Issue by Scheshi** [GravitLauncher/LauncherModules#15]
![unknown-21](https://user-images.githubusercontent.com/47576867/71546456-8e40d400-29c9-11ea-893a-addf6ca0640d.png)
![unknown-32](https://user-images.githubusercontent.com/47576867/71546457-8ed96a80-29c9-11ea-8b83-c88841e3e97a.png)
При билде ошибка "ZipException" и "duplicate entry 'pro/"

**Comment by Istom1n** [comment]
А что помешало ошибку билда выложить?

**Comment by Scheshi** [comment]
> А что помешало ошибку билда выложить?

Ты что глупый?
>При билде ошибка "ZipException" и "duplicate entry 'pro/"

**Comment by Istom1n** [comment]
Рано налетел, я cпросил про лог при билде, а не эти обрывки. Почему-то сделать скриншот запуска тебе не помешало при этом.

**Comment by Scheshi** [comment]
> Рано налетел, я cпросил про лог при билде, а не эти обрывки. Почему-то сделать скриншот запуска тебе не помешало при этом.
> 
> Дикари.

Ньюфаг, ребёнок и заумник устраивает срач на ровном месте на гитхабе. Спешите видеть!
Рано налетел. 
Если я не выложил скрин, значит, на то была причина. Подумай над этим.

Чукча не читатель, чукча писатель, да?

**Comment by gravit0** [comment]
Эти версии модулей для 5.1.1

**Comment by gravit0** [comment]
UPD: Скорее всего LauncherModuleLoader старой версии

**Comment by Scheshi** [comment]
В support/5.0.10 то
