### ISSUE TITLE
Бе ды с DiscordRPC

### ISSUE THREAD

**Issue by Scheshi** [GravitLauncher/LauncherModules#18]
С DiscordRPC на версии 5.1.3 при старте клинта возникает такая ошибка:

> `2020.04.02 04:35:11 [ERROR] java.lang.Error: Invalid memory access
>         at com.sun.jna.Native.invokeVoid(Native Method)
>         at com.sun.jna.Function.invoke(Function.java:415)
>         at com.sun.jna.Function.invoke(Function.java:361)
>         at com.sun.jna.Library$Handler.invoke(Library.java:265)
>         at com.sun.proxy.$Proxy0.Discord_Shutdown(Unknown Source)
>         at pro.gravit.launchermodules.discordrpc.ClientModule.exitHandler(ClientModule.java:73)
>         at pro.gravit.launcher.modules.LauncherModule.callEvent(LauncherModule.java:174)
>         at pro.gravit.launcher.modules.impl.SimpleModuleManager.invokeEvent(SimpleModuleManager.java:257)
>         at pro.gravit.launcher.LauncherEngine.exitLauncher(LauncherEngine.java:64)
>         at pro.gravit.launcher.client.gui.scene.ServerMenuScene.lambda$doLaunchClient$19(ServerMenuScene.java:235)
>         at java.base/java.lang.Thread.run(Thread.java:834)`

Когда игровая активность в дискорде шатдавнится, клиент запускается нормально.

**Comment by Scheshi** [comment]
Вопрос решен. Я снова проебался с кривыми руками своими. Забыл про исключения прогварда.

**Comment by Scheshi** [comment]
2020.04.02 17:04:39 [ERROR] java.lang.Error: Invalid memory access
Даже после добавления исключений.

**Comment by gravit0** [comment]
Попробуй откатить версию JNA и OSHI(взять с 5.0.11)

**Comment by radioegor146** [comment]
А в идеале - скиньте ваш получившийся лаунчер.

**Comment by Zaxar163** [comment]
После недавних коммитов ошибка воспроизводится?

**Comment by Zaxar163** [comment]
Ошибка исправлена в 7a9b5e97a65d9079f3f15e107694e607e8613ed3 8a01cf42f40d0b311a74c4993f36d1aea2623e20
