### ISSUE TITLE
Не работает радон с jarsigner.

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/LauncherModules#2]
Зависает на подписи jarsigner.

**Comment by Zaxar163** [comment]
Пока радон костылить сигнатуры классов не перестанет.

**Comment by TheXaver** [comment]
https://hastebin.com/lonumiwige.rb
если подписывать командой jarsigner

А если модулем jarsigner 
2019.05.23 23:34:21 [INFO]  Task Radon processed from 1816 millis
2019.05.23 23:34:21 [INFO]  Task AttachJars
2019.05.23 23:34:22 [DEBUG] Attaching: /home/launcher/launcher-libraries/commons-logging-1.2.jar
2019.05.23 23:34:22 [DEBUG] Attaching: /home/launcher/launcher-libraries/jfoenix-8.0.8.jar
2019.05.23 23:34:22 [DEBUG] Attaching: /home/launcher/launcher-libraries/httpcore-4.4.11.jar
2019.05.23 23:34:22 [DEBUG] Attaching: /home/launcher/launcher-libraries/slf4j-api-1.7.25.jar
2019.05.23 23:34:22 [DEBUG] Attaching: /home/launcher/launcher-libraries/jna-platform-5.2.0.jar
2019.05.23 23:34:22 [DEBUG] Attaching: /home/launcher/launcher-libraries/jna-5.2.0.jar
2019.05.23 23:34:23 [DEBUG] Attaching: /home/launcher/launcher-libraries/commons-codec-1.11.jar
2019.05.23 23:34:23 [DEBUG] Attaching: /home/launcher/launcher-libraries/httpclient-4.5.7.jar
2019.05.23 23:34:23 [DEBUG] Attaching: /home/launcher/launcher-libraries/oshi-core-3.13.0.jar
2019.05.23 23:34:23 [DEBUG] Attaching: /home/launcher/launcher-libraries/fontawesomefx-8.9.jar
2019.05.23 23:34:23 [INFO]  Task AttachJars processed from 1667 millis
2019.05.23 23:34:23 [INFO]  Task SignJar
то он зависает на 2019.05.23 23:34:23 [INFO]  Task SignJar

**Comment by TheXaver** [comment]
https://pastebin.com/Gn7xSSaV

**Comment by TheXaver** [comment]
Также было бы неплохо добавить timestamp
