### ISSUE TITLE
UnsafeCommandPack: *download команды обрубают stdin

### ISSUE THREAD

**Issue by ijo42** [GravitLauncher/LauncherModules#23]
Тестировалось на версии 5.1.7-dev
При использовании команд закачки с серверов mojang, к примеру, `newdownloadclient` закачка происходит успешно , но после, консоль перестает реагировать на команды, дебаг не дает ничего
https://p.fns.wtf/zuhupiyule.hs

**Comment by JoCat** [comment]
А это довольно таки старая бага))
Как-то хотел про неё написать, но забыл.
Она возможно ещё с 5.0 тянется, если мне память не изменяет.

**Comment by gravit0** [comment]
Есть такое. Пусть Захар решает, его код
