### ISSUE TITLE
Не работает discord RPC

### ISSUE THREAD

**Issue by PEKKAch4KA** [GravitLauncher/LauncherModules#30]
Не работает (соответственно не отображает в дс). Все сделано по инструкциям  с репозитория, конфиг появился и библиотеки присутствуют в /launcher-libraries. Ошибок никаких нету  у клиента тоже ошибок нету, просто предупреждение есть у клиента

`2020.12.17 00:58:47 [WARN] JLine2 isn't in classpath, using std`

![image](https://user-images.githubusercontent.com/42832573/102411769-24b33e80-3ffb-11eb-8b31-a20c6f75c0ef.png)

**Comment by JeffAdventure** [comment]
Перечитайте гайд по Discord RPC. Там все четко и ясно написано. Все прекрасно работает и с ним никаких проблем нет.
Библиотеки /launcher-libraries
Модуль в /launcher-modules
Конфиг в конфиге
Дальше делаешь билд и всё!

**Comment by PEKKAch4KA** [comment]
> Перечитайте гайд по Discord RPC. Там все четко и ясно написано. Все прекрасно работает и с ним никаких проблем нет.
> Библиотеки /launcher-libraries
> Модуль в /launcher-modules
> Конфиг в конфиге
> Настраиваешь Discord Developer portal
> Суешь все в конфиг
> Дальше делаешь билд и всё!

Все пункты выполнены. Дискорд свой напиши

**Comment by DSvinka** [comment]
> Перечитайте гайд по Discord RPC. Там все четко и ясно написано. Все прекрасно работает и с ним никаких проблем нет.
> Библиотеки /launcher-libraries
> Модуль в /launcher-modules
> Конфиг в конфиге
> Настраиваешь Discord Developer portal
> Суешь все в конфиг
> Дальше делаешь билд и всё!

Библиотеки - Засунуты в /launcher-libraries, все версии те которые указаны в реадми
Модуль - Засунут в /launcher-modules
Конфиг - Настроен
Discord DevPortal - Настроен с учётом заметок.
Билд - Сделан

в Jar файле лаунчера DiscordRPC имеется в формате dll.
Но в Discord нечего не отображается.

**Comment by DSvinka** [comment]
Комментарии в конфиге лаунчсервера мешали
