### ISSUE TITLE
Error running command: build

### ISSUE THREAD

**Issue by Gop38883** [GravitLauncher/LauncherModules#35]
![image](https://user-images.githubusercontent.com/59487435/116458964-e7df3a00-a86d-11eb-8acc-4e3158b9d1af.png)
![image](https://user-images.githubusercontent.com/59487435/116459401-6cca5380-a86e-11eb-9471-ddaa34dae03e.png)
i do all but it isn't work

**Comment by gravit0** [comment]
Before 5.2.0-dev openjfx jmods must be copied to JDK/jmods dir

**Comment by Gop38883** [comment]
пж нормально обясни

**Comment by Gop38883** [comment]
куда копирывать?

**Comment by egorsgn3** [comment]
Учите английский, сэр.

**Comment by Gop38883** [comment]
в какую папку кидать? в папку C:\Program Files\Java&

**Comment by egorsgn3** [comment]
Если ты тупой, мы не виноваты.

**Comment by hijuce** [comment]
> в какую папку кидать? в папку C:\Program Files\Java?

в system32

**Comment by Gop38883** [comment]
я кинул и папку jafa fx 11.0.2 в jdk 11.0.2 и файлы в папку jmod и кинул саму папку в system 32 и в и просто фалйли в папку system32

**Comment by Gop38883** [comment]
всё РАБОТАЕТ!
