### ISSUE TITLE
[FEATURE] Скачивание фабрика с официального сервера

### ISSUE THREAD

**Issue by JoCat** [GravitLauncher/LauncherModules#38]
Вместо костыля со скачиванием через установщик можно использовать официальное апи фабрика https://meta.fabricmc.net/

**Comment by microwin7** [comment]
> Вместо костыля со скачиванием через установщик можно использовать официальное апи фабрика https://meta.fabricmc.net/

Реализовано в модуле -> [\[MirrorHelper\]](https://github.com/GravitLauncher/LauncherModules/tree/master/MirrorHelper_module)

**Comment by JoCat** [comment]
👍
