### ISSUE TITLE
MojangSupport_module фатальные баги

### ISSUE THREAD

**Issue by Frysuni** [GravitLauncher/LauncherModules#41]
Авторизация через microsoft - очень полезная вещь в гравите, но только, если бы она работала. репозиторий не обновлялся 2 месяца, подписан, что в разработке, но у меня он совсем не работает. Во-первых не могу нормально выставить окно авторизации, т.к. зараза не может встать правильно
![wtf](https://user-images.githubusercontent.com/86932226/148714028-4ccbcde2-2181-4c76-b3e6-bc692b37666f.png)
Во-вторых, даже если получится поставить его так, что можно нажать кнопку для продолжения он не логинится, а полностью зависает на белом экране вместе с лаунчером
![wtf2](https://user-images.githubusercontent.com/86932226/148714102-8ed2be53-5f3a-4e66-ad14-ebc79d8a4691.png)
Это пока все, что я нашел, т.к. дальше продвинуться просто не могу. У кого-то случалось подобное? Я считаю, что это один из самых важных модулей, которые так же отличают гравит от других форков, да и является полезной фичей, но пока только багом

**Comment by microwin7** [comment]
Здравствуйте, когда модуль был последний раз изменён, он работал нормально, так бы его Гравита не выпустила. Из-за маленького спроса на его, вы первый за долгое время, кто его тестирует и это доходит до нас, мы сожалеем что у вас не получается им воспользоваться в полной мере его функциональности, однако нам нужна дополнительная информация, в виде логов, для того чтоб вам помочь

**Comment by Frysuni** [comment]
Подскажите, как я могу посмотреть логи приложения. Я пробовал запускать через bat jar файл лаунчера, тот закрывается и запускает его с javaagent, только уже без консоли -javaagent:launcher.jar не помогает, требует доп.параметров. В журнале винды тоже ничего не оставляет. Какой еще способ найти логи есть?

**Comment by Frysuni** [comment]
Я вызвал логи. Последнее сообщение от него - вывод WebAuth страницы и все. После верной пары логин/пароль уходит в белый экран(и единоразовое подтверждение соглашение) без продолжения логов
![image](https://user-images.githubusercontent.com/86932226/148726493-92fa37a4-0734-4b8d-972b-a69b3493ea3d.png)
полный лог:
[log.TXT](https://github.com/GravitLauncher/LauncherModules/files/7837156/log.TXT)

**Comment by gravit0** [comment]
Включите `-Dlauncher.dev=true` и повторите попытку. Так же нужны логи лаунчсервера

**Comment by Frysuni** [comment]
java -Xmx256M -Dlauncher.debug=true -Dlauncher.dev=true -Dlauncher.stacktrace=true -javaagent:Launcher.jar -jar Launcher.jar
[logs2.TXT](https://github.com/GravitLauncher/LauncherModules/files/7838543/logs2.TXT)
![screen2](https://user-images.githubusercontent.com/86932226/148760460-499a6ab7-e85d-4b81-8182-b32057b8b656.png)

**Comment by gravit0** [comment]
Вы даже не авторизовались на microsoft судя по логам.

**Comment by Frysuni** [comment]
Это странно, ведь белый экран выводит только при ВЕРНОЙ паре логин/пароль, иначе ошибка входа и все стандартно до момента, когда нужно уже войти. Это происходит и у моего друга на другом аккануте и компьютере

**Comment by gravit0** [comment]
Исправила замеченные проблемы с авторизацией. Полностью проверить не могу.
Обновитесь до dev ветки рантайма, лаунчера и модуля

**Comment by Frysuni** [comment]
Теперь все работает отлично, проблема решена. Спасибо!
![image](https://user-images.githubusercontent.com/86932226/149089024-bf91aaac-ef9e-452f-a8d1-93750a1528d4.png)
![image](https://user-images.githubusercontent.com/86932226/149089048-50be96b6-10a7-49c9-ad23-4e0c98275509.png)
